spring.application.name=taskmanager

# MySQL DB Settings

server.port=${PORT:8080}

spring.datasource.url=${jdbc:postgresql://dpg-d93aj4dckfvc73alglr0-a.virginia-postgres.render.com/taskmanager_db_dg8v}
spring.datasource.username=${taskmanager_db_dg8v_user}
spring.datasource.password=${2CZYnZJn8RjNXPJ8PbIhmWy5Msvdlpld}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sahani.mukesh3142@gmail.com
spring.mail.password=yqkzmjbwsurwrnru
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
